### ISSUE TITLE
Webpacker support?

### ISSUE THREAD

**Issue by gregblass** [foundation/inky-rb#104]
Hey there!

Just wondering if anyone has gotten this to work with webpacker. I was able to start my latest project without using the asset pipeline, but I can't seem to get this to play nice with webpacker no matter what I try.

Thank you!

**Comment by flipsasser** [comment]
I realize I'm way late to help here, @gregblass, but we worked around it by using the `foundation-emails` NPM package and including that from our asset pipeline

**Comment by gregblass** [comment]
Webpacker is no longer the standard in Rails 7. I'd highly recommend avoiding it. It feels so good to not use it.

**Comment by flipsasser** [comment]
Yaw, we ain't usin it either - just trying to be helpful
