### ISSUE TITLE
Status of inky-rb?

### ISSUE THREAD

**Issue by sdhull** [foundation/inky-rb#105]
Just wondering if this ruby gem has essentially be deprecated in favor of https://github.com/foundation/inky

I was thinking about using this for a project but I don't want to use it if it's no longer the blessed path and it would be significantly more difficult to use the npm package (given my constraints).

**Comment by marcandre** [comment]
This rubygem is meant to track `inky`; both are very stable though so one shouldn't expect frequent releases.
Please open an issue if you are aware of a discrepancy with `inky`
