### ISSUE TITLE
Missing support for <h-line>

### ISSUE THREAD

**Issue by pilaf** [foundation/inky-rb#106]
Hello, I noticed that inky-rb is lacking support for `<h-line>` (unlike https://github.com/foundation/inky).

(Thank you for this great tool!)

**Comment by marcandre** [comment]
Interesting. Do you actually use `<h-line>`? It seems to be [completely broken](https://github.com/foundation/inky/issues/137) on `inky`, or am I missing something.

In any case I'll implement it.

**Comment by marcandre** [comment]
Released v1.4.2.0
